public with sharing class Category {
	
	public String ID  {get;set;}
	public String catObjCode  {get;set;}
	public String customerID  {get;set;}
	public String description  {get;set;}
	public String enteredByID  {get;set;}
	public String extRefID  {get;set;}
	public String groupID  {get;set;}
	public String lastUpdatedByID  {get;set;}
	public String name  {get;set;}
	public dateTime lastUpdateDate  {get;set;}
	public boolean hasCalculatedFields  {get;set;}

}