public with sharing class Document_Folder {
	
	public String ID  {get;set;}
	public String customerID  {get;set;}
	public String enteredByID  {get;set;}
	public String issueID  {get;set;}
	public String iterationID  {get;set;}
	public String name  {get;set;}
	public String parentID  {get;set;}
	public String portfolioID  {get;set;}
	public String programID  {get;set;}
	public String projectID  {get;set;}
	public String securityRootID  {get;set;}
	public String securityRootObjCode  {get;set;}
	public String taskID  {get;set;}
	public String templateID  {get;set;}
	public String templateTaskID  {get;set;}
	public String userID  {get;set;}
	public dateTime entryDate  {get;set;}

	

}