public with sharing class Iteration {
	
	public String ID  {get;set;}
	public String URL  {get;set;}
	public String categoryID  {get;set;}
	public String customerID  {get;set;}
	public String enteredByID  {get;set;}
	public String goal  {get;set;}
	public String lastUpdatedByID  {get;set;}
	public String name  {get;set;}
	public String ownerID  {get;set;}
	public String startDate  {get;set;}
	public String teamID  {get;set;}
	public double capacity  {get;set;}
	public double estimateCompleted  {get;set;}
	public double focusFactor  {get;set;}
	public double percentComplete  {get;set;}
	public double targetPercentComplete  {get;set;}
	public double totalEstimate  {get;set;}
	public dateTime endDate  {get;set;}
	public dateTime entryDate  {get;set;}
	public dateTime lastUpdateDate  {get;set;}
	public dateTime start_Date  {get;set;}
	public String[] taskIDs  {get;set;}
	public boolean hasDocuments  {get;set;}
	public boolean hasNotes  {get;set;}


	

}