public with sharing class Layout_Template {
	
	public String ID  {get;set;}
	public String appGlobalID  {get;set;}
	public String customerID  {get;set;}
	public String defaultNavItem  {get;set;}
	public String description  {get;set;}
	public String descriptionKey  {get;set;}
	public String extRefID  {get;set;}
	public String lastUpdatedByID  {get;set;}
	public String licenseType  {get;set;}
	public String name  {get;set;}
	public String nameKey  {get;set;}
	public String navBar  {get;set;}
	public String objID  {get;set;}
	public String objObjCode  {get;set;}
	public dateTime lastUpdateDate  {get;set;}
	public String[] navItems  {get;set;}
		

}