public with sharing class Note {
	
	public String ID  {get;set;}
	public String attachDocumentID  {get;set;}
	public String attachObjCode  {get;set;}
	public String attachObjID  {get;set;}
	public String attachOpTaskID  {get;set;}
	public String auditText  {get;set;}
	public String auditType  {get;set;}
	public String customerID  {get;set;}
	public String documentID  {get;set;}
	public String extRefID  {get;set;}
	public String formatEntryDate  {get;set;}
	public String iterationID  {get;set;}
	public String noteObjCode  {get;set;}
	public String noteText  {get;set;}
	public String objID  {get;set;}
	public String opTaskID  {get;set;}
	public String ownerID  {get;set;}
	public String parentEndorsementID  {get;set;}
	public String parentJournalEntryID  {get;set;}
	public String parentNoteID  {get;set;}
	public String portfolioID  {get;set;}
	public String programID  {get;set;}
	public String projectID  {get;set;}
	public String referenceObjectName  {get;set;}
	public String securityRootID  {get;set;}
	public String securityRootObjCode  {get;set;}
	public String subject  {get;set;}
	public String taskID  {get;set;}
	public String templateID  {get;set;}
	public String templateTaskID  {get;set;}
	public String threadID  {get;set;}
	public String timesheetID  {get;set;}
	public String topNoteObjCode  {get;set;}
	public String topObjID  {get;set;}
	public String topReferenceObjectName  {get;set;}
	public String userID  {get;set;}
	public Integer indent  {get;set;}
	public Integer numLikes  {get;set;}
	public Integer numReplies  {get;set;}
	public dateTime entryDate  {get;set;}
	public dateTime threadDate  {get;set;}
	public boolean emailUsers  {get;set;}
	public boolean hasReplies  {get;set;}
	public boolean isDeleted  {get;set;}
	public boolean isMessage  {get;set;}
	public boolean isPrivate  {get;set;}
	public boolean isReply  {get;set;}
	
	public void Like1(){
		
	}
	
	public void Unlike(){
		
	}

}